service:
  name: notify-app

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  profile: mibuilding
  region: us-east-1
  memorySize: 512
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "*"
    

functions:
  new-note:
    handler: handler.putData
    events:
      - http:
          method: POST
          path: /
          cors: true
          request:
            schema:
              application/json: ${file(schemas/notes-post.json)}
  get-items:
    handler: handler.getData
    events:
      - http:
          method: GET
          path: /
          cors: true
  complete-item:
    handler: handler.completeItem
    events:
      - http:
          method: PATCH
          path: /{ID}
          cors: true
          request:
            parameters:
              ID: true
