service:
  name: notify-app

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  profile: asad
  region: us-east-1
  memorySize: 512
  iamRoleStatements:
  - Effect: 
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "*"
    

functions:
  second:
    handler: handler.putData
    events:
      - http:
          method: get
          path: /
          cors: true
          request:
            schema:
              application/json: ${schemas/notes-post.json)}
